apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deploy
  namespace: argocd    
  labels:
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app     
    spec:
      containers:
        - name: simple-app
          image: ijcheon/simple_app:0.2
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: properties
            mountPath: /app/properties
      volumes:
       - name: properties
         hostPath:
          path: /Users/chenchen/Desktop/dev/simpleApp
          type: DirectoryOrCreate
