apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vas-svc.yaml
- vas-deploy.yaml
- vas-ing.yaml
images:
- name: ijcheon/vas
  newTag: 0.0.1 #버전만 바꿔주면 yaml 파일의 버전을 알아서 업데이트한다.
